### PR TITLE
Make unity materials from TXMT files.

### PR DESCRIPTION
**Pull request by ammaraskar**
This adds the StandardMaterial TXMT from the game. We use a simple Lambert surface shader to handle its rendering. Unfortunately since there's no easy way in unity to make a surface shader with different alpha modes based on the shader feature this means we need a shader per each type of alpha mode: Opaque, CutOut and Blend.

This does lead to some duplicated code in the shaders in terms of the properties but the body of the shader is stored in a common .cginc file that gets pulled in with a #include

---

Here's what the strangetown crashed ufo looks like now with its transparent cabin and pre-baked transparent shadow:

image

I haven't handled the other properties like material diffusivity and such yet but this looks much better than the standard PBR shader.

### CODE REVIEW

**Review by LazyDuchess — CHANGES_REQUESTED** [review]
The Material returned by the Asset should be cached into a variable in the Asset, and "public override UnityEngine.Object[] GetUnmanagedResources()" should be overriden in the Asset to return the Material (and any other unmanaged Unity object the Asset might have).

This way these objects get released by the new MemoryController when they're no longer in use.

**Comment by LazyDuchess** [comment]
Looks good otherwise! Just keep in mind that we have to keep references to Assets in use and implement GetUnmanagedResources() to avoid any memory leaks and to make sure that things that we are using stay in memory.

**Comment by ammaraskar** [comment]
Gotcha, done. Will keep that in mind for future assets.

**Comment by LazyDuchess** [comment]
Perfect!

**Pull request merged**
